New Launchpad design
Origin-Byte/nft-protocol pull request #107
Opened 2022-11-28 15:32 UTC by nmboavida

2022-11-29 13:29 UTC, bausano commented on sources/launchpad/launchpad.move
> +    struct Launchpad<phantom T> has key, store{
```suggestion
    struct Launchpad<phantom T> has key, store {
```

2022-11-29 13:29 UTC, bausano commented on sources/launchpad/launchpad.move
> +    struct Trebuchet has key, store{
```suggestion
    struct Trebuchet has key, store {
```

2022-11-29 13:29 UTC, bausano commented on sources/launchpad/launchpad.move
> +        /// The address of the administrator
```suggestion
```

2022-11-29 13:29 UTC, bausano commented on sources/launchpad/launchpad.move
> +        admin: address,
There's already an admin field on the `Launchpad` itself. Can it happen that those two mismatch?

2022-11-29 13:29 UTC, bausano commented on sources/launchpad/launchpad.move
> +        collections: vector<ID>,
So one trebuchet can have many collections, and one launchpad many trebuchets then

2022-11-29 13:30 UTC, bausano commented on sources/launchpad/launchpad.move
> +        launchpad: &mut Launchpad<T>,
How do I instantiate `Launchpad` in the first place? Should we take this as a param, or should we just return a `Launchpad<T>` from this method?

2022-11-29 13:31 UTC, bausano commented on sources/launchpad/launchpad.move
> +    // /// Burn the `Trebuchet`
TODO

2022-11-29 13:32 UTC, bausano commented on sources/launchpad/launchpad.move
> +        slingshot.live = true
you need to check that the lauchpad owns this trebuchet I believe

2022-11-29 13:32 UTC, bausano commented on sources/launchpad/launchpad.move
> +        slingshot.live = false
you need to check that the lauchpad owns this trebuchet I believe

2022-11-29 13:32 UTC, bausano commented on sources/launchpad/launchpad.move
> +        vector::push_back(&mut slingshot.markets, market);
you need to check that the lauchpad owns this trebuchet I believe

2022-11-29 13:32 UTC, bausano commented on sources/launchpad/launchpad.move
> +    public fun id<T>(
`object::id(&slightshot)` works too, I'd remove this method

2022-12-06 14:00 UTC, nmboavida commented on sources/launchpad/launchpad.move
> +        collections: vector<ID>,
That's right, however we need to reconsider how the flow of a sale with multiple collections in the next iterations

2022-12-06 14:01 UTC, nmboavida commented on sources/launchpad/launchpad.move
> +    // /// Burn the `Trebuchet`
Added TODO

2022-12-06 14:02 UTC, nmboavida commented on sources/launchpad/launchpad.move
> +        vector::push_back(&mut slingshot.markets, market);
Done

2022-12-06 14:02 UTC, nmboavida commented on sources/launchpad/launchpad.move
> +        slingshot.live = true
Done

2022-12-06 14:03 UTC, nmboavida commented on sources/launchpad/launchpad.move
> +        launchpad: &mut Launchpad<T>,
Updated to:

```
public entry fun init_launchpad(
        admin: address,
        receiver: address,
        auto_approval: bool,
        default_fee: ObjectBox,
        ctx: &mut TxContext,
    )
```

2022-12-06 14:04 UTC, nmboavida commented on sources/launchpad/launchpad.move
> +        admin: address,
Now there are essentially two admins, the Launchpad and the Slot admin

2022-12-06 15:03 UTC, Suficio requested changes

2022-12-06 15:03 UTC, Suficio commented on sources/utils/box.move
> +module nft_protocol::box {
If Box is unused then we should leave it out of the MR

2022-12-06 15:25 UTC, bausano commented on sources/utils/err.move
> +        return Prefix + 212
Same error code as above, is that intentional?

2022-12-06 15:26 UTC, bausano commented on sources/utils/err.move
> +    // === Generic ===
```suggestion
    // === Generic ===

```

2022-12-06 15:28 UTC, bausano commented on sources/launchpad/whitelist.move
can we rename this module to `nft_protocol::launchpad_whitelist`, to make it easy to recognize from `nft_protocol::transfer_whitelist`. I'd keep the file name, just rename the module.

2022-12-06 15:30 UTC, bausano commented on sources/launchpad/proceeds.move
> +        total: u64,
perhaps a comment - total of what?

2022-12-06 15:31 UTC, bausano commented on sources/launchpad/proceeds.move
> +        total: u64,
does this total make sense tho? because we're adding basically different fungible tokens

like this would be sum of all tokens in all mints, is that a useful information?

2022-12-06 19:59 UTC, nmboavida commented on sources/launchpad/launchpad.move
> +        is_embedded: bool,
Removed

2022-12-06 19:59 UTC, nmboavida commented on sources/launchpad/launchpad.move
> +    /// Adds a sale outlet `Outlet` to `sales` field
Resolved

2022-12-06 20:01 UTC, nmboavida commented on sources/utils/box.move
> +module nft_protocol::box {
Removed

2022-12-06 20:02 UTC, nmboavida commented on sources/nft/nft.move
> +    public fun id<T>(
Removed

2022-12-06 20:20 UTC, nmboavida commented on sources/utils/err.move
> +    public fun wrong_admin(): u64 {
I changed the name from wrong_admin() to `wrong_launchpad_or_slot_admin()`. This is in the case where the caller is either the slot or the launchpad admin, but errs if neither

2022-12-06 20:20 UTC, nmboavida commented on sources/utils/err.move
> +        return Prefix + 212
It was a mistake, I fixed it now

2022-12-06 20:23 UTC, nmboavida commented on sources/launchpad/proceeds.move
> +    // public fun destroy_zero<FT>(
Added

2022-12-07 10:10 UTC, nmboavida commented on examples/suimarines.move
> -        fixed_price::create_market(
The flow is now the following:

1. Marketplace creates Launchpad
2. X creates a slot in the launchpad for an NFT Collection release (X can be the Marketplace or the NFT creator - if its the Marketplace the slot will be automatically approved, otherwise if its the NFT Creator creating the slot then it will only be automaticall approved if the flag `auto_approval = true`, otherwise the Marketplace has to approve it on their side)
3. Marketplace or NFT Creator can then add markets to the slot

In relation to collections, the launchpad markets are now agnostic to the collection type which means that multiple collections can be sold in the same market. We still need to work on this workflow a little bit more but the idea is that in the future you could sell NFTs from different collections in a bundle.

2022-12-07 10:11 UTC, nmboavida commented on sources/launchpad/fees/fixed_fees.move
> +module nft_protocol::flat_fee {
Makes a lot of sense, we can try to generalise fees/commissions/royalties, one thing to be cautious however is that in the case of the launchpad, fees can be charge in the bulk of the service instead of individual sales.

2022-12-07 10:22 UTC, nmboavida commented on sources/launchpad/whitelist.move
Addressed

2022-12-07 10:32 UTC, nmboavida commented on sources/launchpad/proceeds.move
> +        total: u64,
My initial idea was that proceeds were all to be in the same fungible token and that therefore `Proceeds.total` would be the total of those proceeds. The reason for storing that info is to allow for custom types of fees that rely on the total FT-amount sold. Marketplaces could then reduce the amount of fees charged based on the bulk-volume of the sale. 

The same goes for `Sold` which is have renamed it to:

```
// Quantity of NFTs Sold
struct QtSold has copy, drop, store {
    // Bookeeping of all NFT sold whose proceeds have been withdrawn.
    collected: u64,
    // Total number of NFTs sold. The reason for storing this info is to
    // allow for custom types of fees that rely on the total FT-amount sold.
    // Marketplaces could then reduce the amount of fees charged based
    // on the bulk-volume of the sale.
    total: u64,
}
```


I have also added a TODO to reconsider `Proceeds.total` .

2022-12-07 11:26 UTC, nmboavida commented on examples/suimarines.move
> +    public entry fun mint_nft(
Removed

2022-12-07 11:30 UTC, Suficio approved these changes

2022-12-07 11:31 UTC, merged