Feature: Launchpad minting flow
Origin-Byte/nft-protocol pull request #129
Opened 2022-12-08 12:42 UTC by nmboavida

2022-12-08 13:48 UTC, Suficio requested changes

2022-12-08 13:48 UTC, Suficio commented on sources/launchpad/launchpad.move
>          market: ObjectBox,
If we replace `ObjectTable<ID, ObjectBox>` with `ObjectBag` this could be a potential solution?

```suggestion
    public entry fun add_market<Market>(
        launchpad: &Launchpad,
        slot: &mut Slot,
        market: Market,
```

2022-12-08 13:48 UTC, Suficio commented on sources/launchpad/launchpad.move
> +        dof::add(
Is dof also susceptible to the 2MB limit?
We might need to store NFTs in an explicit `ObjectBag`.

2022-12-08 13:48 UTC, Suficio commented on sources/launchpad/market/dutch_auction.move
> +        // inventory: Inventory,
```suggestion
```

2022-12-08 13:48 UTC, Suficio commented on sources/launchpad/market/dutch_auction.move
> +
```suggestion
```

2022-12-08 16:42 UTC, Suficio commented on examples/suimarines.move
> +        name: vector<u8>,
Actually, lets leave this, I think this approach makes most sense.

2022-12-08 18:07 UTC, nmboavida commented on sources/launchpad/launchpad.move
> +        dof::add(
My understanding is that dofs are not susceptible to the 2MB limit

2022-12-08 18:36 UTC, nmboavida commented on sources/launchpad/market/fixed_price.move
> +        };
Done :)

2022-12-08 20:47 UTC, Suficio approved these changes
LGTM

2022-12-09 09:47 UTC, nmboavida commented on sources/launchpad/market/fixed_price.move
> +        // TODO: Reconsider safety of inventory_mut
Created :saluting_face:

2022-12-09 09:48 UTC, merged