Tests: NFT domains
Origin-Byte/nft-protocol pull request #151
Opened 2022-12-15 09:23 UTC by nmboavida

2022-12-15 12:47 UTC, bausano commented on sources/nft/nft.move
> +    #[test_only]
I reckon we can export this as a non test getter too

2022-12-15 12:48 UTC, bausano commented on tests/domains/display.move
> +        );
perhaps another statement that attempts to `get_domain<DisplayDomain>` so that if this method was a no-op the test case would fail

2022-12-15 12:48 UTC, bausano approved these changes

2022-12-15 12:54 UTC, Suficio requested changes

2022-12-15 12:54 UTC, Suficio commented on tests/nft.move
> +    // fun borrows_domain_mut() {
Do we fix this now?

2022-12-15 13:51 UTC, Suficio requested changes

2022-12-15 13:51 UTC, Suficio commented on tests/nft.move
> +
Double spacing

2022-12-15 14:03 UTC, nmboavida commented on sources/nft/nft.move
> +    #[test_only]
Done

2022-12-15 14:18 UTC, nmboavida commented on tests/nft.move
> +    // fun borrows_domain_mut() {
Done

2022-12-15 22:35 UTC, nmboavida commented on tests/domains/display.move
> +        );
Oh that's right, I just added it to all tests, thanks!

2022-12-16 07:13 UTC, Suficio approved these changes

2022-12-16 08:40 UTC, merged