Kiosk Policies
Origin-Byte/nft-protocol pull request #375
Opened 2023-04-19 04:04 UTC by nmboavida

2023-04-19 11:21 UTC, bausano commented on sources/kiosk/policies/borrow.move
> +        field: Option<TypeName>,
could you add a comment for what does this bit work do please

2023-04-19 11:22 UTC, bausano commented on sources/kiosk/policies/borrow.move
> +    ): &mut RequestBody<WithNft<T, BORROW_REQUEST>> { &mut self.inner }
Nice, I think it's gonna work great with allowlist, it can now be reused for `OB_TRANSFER_REQUEST` and `BORROW_REQUEST` or `WITHDRAW_REQUEST`.

2023-04-19 11:23 UTC, bausano approved these changes

2023-04-19 15:14 UTC, Suficio requested changes
Not sure that I see the benefit of separating `TransferRequest` and `WithdrawalRequest`.

Intuitively the only difference between the two is that `TransferRequest` is a `WithdrawalRequest` that requires a final receipt of being deposited in another `Kiosk`.

2023-04-20 09:55 UTC, Suficio approved these changes

2023-04-20 10:25 UTC, nmboavida commented on sources/kiosk/policies/borrow.move
> +        field: Option<TypeName>,
We will reorganize things a little bit later today and add comments

2023-04-20 10:26 UTC, merged