Complete orderbook migration
Origin-Byte/nft-protocol pull request #472
Opened 2023-05-29 07:41 UTC by nmboavida

2023-05-30 09:50 UTC, Suficio requested changes

2023-05-30 09:50 UTC, Suficio commented on contracts/liquidity_layer_v1/sources/trading/orderbook.move
> +    }
```suggestion
    fun assert_version_and_upgrade<T: key + store, FT>(self: &mut Orderbook<T, FT>) {
        if (self.version < VERSION) {
            self.version = VERSION;
        };
        assert_version(self);
    }
```

2023-05-30 09:50 UTC, Suficio commented on contracts/liquidity_layer_v1/sources/trading/orderbook.move
> +        let price = crit_bit::max_key(&book.asks);
Would it make sense to provide an API where the user has to provide the price level and NFT ID such that they can migrate in their own order?

2023-05-30 09:50 UTC, Suficio commented on contracts/liquidity_layer_v1/sources/trading/orderbook.move
> +        ob_kiosk::assert_has_nft(kiosk, ask.nft_id);
We should delegate the signer immediately within this function

2023-05-30 09:50 UTC, Suficio commented on contracts/nft_protocol/sources/rules/royalty_strategy.move
> +        abort(0)
Could you use a special error code for deprecated API?

2023-05-30 11:19 UTC, nmboavida commented on contracts/kiosk/sources/kiosk/ob_kiosk.move
> +        assert!(ref.is_exclusively_listed, ENotAuthorized);
Removed second assert 👍

2023-05-30 11:22 UTC, nmboavida commented on contracts/liquidity_layer_v1/sources/trading/orderbook.move
> +    }
Changed 👍

2023-05-30 11:34 UTC, nmboavida commented on contracts/liquidity_layer_v1/sources/trading/orderbook.move
> +        ob_kiosk::assert_has_nft(kiosk, ask.nft_id);
The challenge in doing so is that we would need to provide a reference to `book_v2.id`, and I would like to keep the V2 API as clean as possible and not have any function that exposes its UID. The only function added to book_v2 is `insert_ask_as_witness` and doing the delegation here guarantees that there is no possible attack vector that would result in an exposed orderbook V2 UID.

To simplify, I added the functions from the migrate module to the orderbook module and made `migrate_ask_` and `migrate_bid_` private, so the flow is clear that if `migrate_ask_` is called, then `insert_ask_as_witness` will be inevitably called.

2023-05-30 11:37 UTC, nmboavida commented on contracts/nft_protocol/sources/rules/royalty_strategy.move
> +        abort(0)
Done 👍

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +    // TODO: This DF Key does not need to have generics, as the generics are
If we are upgrading the contract then we can remove them?

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +        let book_v1_id = df::borrow(&book.id, UnderMigrationFrom {});
Can you create a special method `assert_under_migration` that checks if `UnderMigrationFrom` exists and throws a custom error code if it doesn't?

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +            object::uid_to_inner(book_v1_uid) == *book_v1_id, 0
Use a custom error code

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +            object::uid_to_inner(book_v1_uid) == *book_v1_id, 0
Custom error code

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +        let book_v1_id = df::borrow(&book.id, UnderMigrationFrom {});
Same as `assert_under_migration`

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +        set_protection_with_witness(witness, book, false, false, false);
I would remove this line as the `Orderbook` may have been previously protected and it is not immediately obvious that trading should start as soon as the migration is complete.

I would also like to see `set_protection_with_witness` abort if `UnderMigrationFrom` exists.

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +        df::add(&mut book_v2.id, UnderMigrationFrom {}, book_v1_id);
Here I see you register `UnderMigrationFrom` on V2, but you later try borrow the df from the V1 in `migrate_bid_v1`?

Is this right or am I misunderstanding something?

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer_v1/sources/trading/orderbook.move
> +    use ob_permissions::witness::{Witness as DelegatedWitness};
```suggestion
    use ob_permissions::witness::Witness as DelegatedWitness;
```

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +    struct UnderMigrationFrom has copy, store, drop {}
```suggestion
    struct UnderMigrationFromDfKey has copy, store, drop {}
```

Would be nice to have some context hints as to what the type is meant to be used for?

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +    struct UnderMigrationFrom has copy, store, drop {}
This would apply to all the other df markers in this PR.

2023-05-31 07:48 UTC, Suficio commented on contracts/liquidity_layer_v1/sources/trading/orderbook.move
> +        trading::transfer_ask_commission<FT>(
Could you add a comment as to what is happening here?

2023-05-31 16:43 UTC, nmboavida commented on contracts/kiosk/sources/kiosk/ob_kiosk.move
> +        assert!(ref.is_exclusively_listed, ENotAuthorized);
Removed first assert

2023-05-31 16:50 UTC, nmboavida commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +        let book_v1_id = df::borrow(&book.id, UnderMigrationFrom {});
Done

2023-05-31 16:55 UTC, nmboavida commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +            object::uid_to_inner(book_v1_uid) == *book_v1_id, 0
Added `EIncorrectOrderbookV1`

2023-05-31 16:56 UTC, nmboavida commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +            object::uid_to_inner(book_v1_uid) == *book_v1_id, 0
Added `EIncorrectOrderbookV1`

2023-05-31 16:56 UTC, nmboavida commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +        let book_v1_id = df::borrow(&book.id, UnderMigrationFrom {});
Done

2023-05-31 17:00 UTC, nmboavida commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +        set_protection_with_witness(witness, book, false, false, false);
Done

2023-05-31 17:24 UTC, nmboavida commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +        df::add(&mut book_v2.id, UnderMigrationFrom {}, book_v1_id);
The core idea was to give authority to the orderbook V1 to call `migrate_bid_v1` `migrate_ask_v1` without having to import it as a dependency. So the creator can call `orderbook_v1::start_migration_to_v2` and `orderbook_v2::start_migration_from_v1` to let the orderbooks know about each other. Then when we call `orderbook_v1::migrate_ask`, we check that the OrderbookV2 referred in the parameters is the correct one. Then, when this function calls `orderbook_v2::migrate_ask_v1` it checks if the `&UID` from the `OrderbookV1` provided is the correct one

2023-05-31 17:26 UTC, nmboavida commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +    struct UnderMigrationFrom has copy, store, drop {}
Done

2023-05-31 17:28 UTC, nmboavida commented on contracts/liquidity_layer_v1/sources/trading/orderbook.move
> +        trading::transfer_ask_commission<FT>(
Added `// Sell-side commission gets transferred to the sell-side intermediary`

2023-06-01 07:20 UTC, nmboavida commented on contracts/liquidity_layer/sources/trading/orderbook.move
> +    // TODO: This DF Key does not need to have generics, as the generics are
Done

2023-06-01 08:22 UTC, nmboavida commented on contracts/kiosk/sources/kiosk/ob_kiosk.move
> +        new_entity: &UID,
Done

2023-06-02 15:13 UTC, merged