Fix dangling locks
Origin-Byte/nft-protocol pull request #481
Opened 2023-06-07 12:01 UTC by nmboavida

2023-06-07 12:03 UTC, tomfurrier approved these changes

2023-06-07 12:05 UTC, Suficio requested changes

2023-06-07 12:05 UTC, Suficio commented on contracts/kiosk/sources/kiosk/ob_kiosk.move
> +        // Delegated withdraws need to be settled via `withdraw_nft`
Should you also add this assert to `withdraw_nft`?

2023-06-08 07:40 UTC, nmboavida commented on contracts/kiosk/sources/kiosk/ob_kiosk.move
> +        // Delegated withdraws need to be settled via `withdraw_nft`
The withdraw_nft requires a prior authorisation, which itself asserts if the NFT is being exclusively locked

2023-06-08 07:46 UTC, merged