Draft: NFT Orderbook
Origin-Byte/nft-protocol pull request #56
Opened 2022-11-02 21:49 UTC by bausano

2022-12-06 12:56 UTC, Suficio requested changes

2022-12-06 12:56 UTC, Suficio commented on sources/trading/ob.move
> +        whitelist: &Whitelist,
Are there any safety checks that `Whitelist` must pass, seems like anyone can pass their own whitelist that allows the transfer of NFTs by the OB?

2022-12-06 13:07 UTC, bausano commented on sources/trading/ob.move
> +        whitelist: &Whitelist,
Yes, the collection creator must agree that their collection is added to the whitelist. If you create your own whitelist, OB won't be able to transfer the NFT unless SUIMARINES creators agreed to be part of your whitelist.

2022-12-15 08:50 UTC, Suficio approved these changes

2022-12-15 08:50 UTC, Suficio commented on sources/trading/ob.move
> +    }
Spacing, in other places as well

2022-12-15 08:50 UTC, Suficio commented on sources/trading/ob.move
> +    fun create_<C, FT>(
Could this be `public fun new`?

2022-12-15 08:50 UTC, Suficio commented on sources/trading/ob.move
> +    public fun toggle_protection_on_buy_nft<W: drop, C, FT>(
Lets merge this as is, but would be good to make this explicit, `enable_protection_on_buy_nft`, `disable_protection_on_buy_nft`.

2022-12-15 09:00 UTC, bausano commented on sources/trading/ob.move
> +            // OPTIMIZE: this is being recomputed
done

2022-12-15 09:05 UTC, merged