Cleanup errors and prelude
Origin-Byte/nft-protocol pull request #78
Opened 2022-11-14 13:42 UTC by Suficio

- Cleans up `GutenError` cases
- Cleans up `prelude`, which should be used to export crate types not std types

2022-11-16 12:02 UTC, nmboavida requested changes

2022-11-18 11:45 UTC, bausano commented on gutenberg/src/schema.rs
> +            strfmt::strfmt(&fmt, &vars)
Why do we repeat repeat ourselves?

2022-11-22 10:11 UTC, Suficio commented on gutenberg/src/err.rs
> +    SerdeYaml(#[from] serde_yaml::Error),
Done, this happened because we were parsing a `Box<str>`, switched it out for `u64`.
I'll also prepare a second PR cleaning up input type handling.

2022-11-22 15:05 UTC, Suficio commented on gutenberg/src/err.rs
> -        );
Best error message that I could get serde_yaml to generate is:

```Launchpad.market_type.reserve_prices: invalid type: integer `1000`, expected a sequence at line 18 column 21`

But this also requires a syntax change to:

```yaml
Launchpad:
  market_type: !Auction
    reserve_prices: 1000
    whitelists: [true, false]
```

If we would like to reintroduce friendly error messages, then we would have to manually implement `Deserialize` for each of our structs.

2022-11-23 11:47 UTC, Suficio commented on gutenberg/src/schema.rs
> +            strfmt::strfmt(&fmt, &vars)
Removed

2022-11-23 14:15 UTC, nmboavida commented on gutenberg/src/err.rs
> -        );
That's fine, we can consider readding this in the future, but we won't possibly need it as we will try to not get users composing the yaml file directly but via CLI.

2022-11-23 14:22 UTC, nmboavida approved these changes

2022-11-23 14:23 UTC, merged